from enum import Enum


class SubjectType(str, Enum):
    USER = "USER"
    TEAM = "TEAM"
    UNKNOWN = "UNKNOWN"


class SourceType(str, Enum):
    PROJECT_FILE = "PROJECT_FILE"
    QUICK_LOG = "QUICK_LOG"


class AnalysisResultType(str, Enum):
    EXISTING_UPDATE = "EXISTING_UPDATE"
    NEW_EXPERIENCE = "NEW_EXPERIENCE"
    NEEDS_CONTEXT = "NEEDS_CONTEXT"
    NO_UPDATE = "NO_UPDATE"


class InformationNeedType(str, Enum):
    USER_ANSWER = "USER_ANSWER"
    ADDITIONAL_SOURCE = "ADDITIONAL_SOURCE"


class SourceWarningType(str, Enum):
    POSSIBLE_PROJECT_MISMATCH = "POSSIBLE_PROJECT_MISMATCH"


class SourceWarningAction(str, Enum):
    EXCLUDE_FROM_ANALYSIS = "EXCLUDE_FROM_ANALYSIS"
    INCLUDE_ANYWAY = "INCLUDE_ANYWAY"


class ProvenanceType(str, Enum):
    SOURCE_EXTRACTED = "SOURCE_EXTRACTED"
    AI_INFERRED = "AI_INFERRED"
    USER_INPUT = "USER_INPUT"
    USER_CONFIRMED = "USER_CONFIRMED"
    USER_EDITED = "USER_EDITED"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    REJECTED = "REJECTED"


class EvidenceType(str, Enum):
    DIRECT = "DIRECT"
    INDIRECT = "INDIRECT"
    NONE = "NONE"


class PolicyViolationType(str, Enum):
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    UNSUPPORTED_USER_CONTRIBUTION = "UNSUPPORTED_USER_CONTRIBUTION"
    TEAM_TO_USER_ATTRIBUTION = "TEAM_TO_USER_ATTRIBUTION"
    UNSUPPORTED_ACHIEVEMENT = "UNSUPPORTED_ACHIEVEMENT"
    UNSUPPORTED_ROLE = "UNSUPPORTED_ROLE"
    CONTRADICTORY_CLAIM = "CONTRADICTORY_CLAIM"
    INVALID_SOURCE_REFERENCE = "INVALID_SOURCE_REFERENCE"
    INVALID_PROVENANCE = "INVALID_PROVENANCE"
