spring:
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true